apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bishop-app
spec:
  template:
    spec:
      containers:
        - image: gcr.io/annular-strata-455623-g5/bishop-app
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "256Mi"
          env:
            - name: NODE_ENV
              value: "production" 