name: Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Configure Docker to use GCP Artifact Registry
      - name: Configure Docker for GCP Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/bdarch-bishop/bishop/backend:latest ./backend

      # Push the Docker image to GCP Artifact Registry
      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/bdarch-bishop/bishop/backend:latest